<!-- filepath: e:\Apps\authrix\.github\ISSUE_TEMPLATE\config.yml -->
blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/Grenish/authrix/blob/main/README.md
    about: Check the documentation for usage examples and API reference
  - name: 🔒 Security Issue
    url: https://github.com/Grenish/authrix/security/advisories/new
    about: Report a security
